//
//  TodoListRouter.swift
//  TodoList
//
//  Created by 60058232 on 2021/01/20.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TodoListRoutingLogic
{
	func routeToCreateTodo(segue: UIStoryboardSegue?)
	func routeToTodoDetail(segue: UIStoryboardSegue?)
}

protocol TodoListDataPassing
{
	var dataStore: TodoListDataStore? { get set }
}

class TodoListRouter: NSObject, TodoListRoutingLogic, TodoListDataPassing
{

	weak var viewController: TodoListViewController?
	var dataStore: TodoListDataStore?

	// MARK: Routing

	func routeToCreateTodo(segue: UIStoryboardSegue?)
	{
		if segue == nil {
			let storyboard = UIStoryboard(name: "Main", bundle: nil)
			let destinationVC = storyboard.instantiateViewController(withIdentifier: "CreateTodoViewController") as! CreateTodoViewController
			navigateToCreateTodo(source: viewController!, destination: destinationVC)
		}
	}

	func routeToTodoDetail(segue: UIStoryboardSegue?)
	{
		if let segue = segue {
			let destinationVC = segue.destination as! TodoDetailViewController
			var destinationDS = destinationVC.router!.dataStore!
			passDataToTodoDetail(source: dataStore!, destination: &destinationDS)
		} else {
			let storyboard = UIStoryboard(name: "Main", bundle: nil)
			let destinationVC = storyboard.instantiateViewController(withIdentifier: "TodoDetailViewController") as! TodoDetailViewController
			var destinationDS = destinationVC.router!.dataStore!
			passDataToTodoDetail(source: dataStore!, destination: &destinationDS)
			navigateToTodoDetail(source: viewController!, destination: destinationVC)
		}
	}

	// MARK: Navigation

	func navigateToCreateTodo(source: TodoListViewController, destination: CreateTodoViewController)
	{
		source.show(destination, sender: nil)
	}

	func navigateToTodoDetail(source: TodoListViewController, destination: TodoDetailViewController)
	{
		source.show(destination, sender: nil)
	}


	// MARK: Passing data

	func passDataToTodoDetail(source: TodoListDataStore, destination: inout TodoDetailDataStore)
	{
		let indexPath : IndexPath = (viewController?.todoTableView.indexPathForSelectedRow!)!

		let selectedTodo = viewController?.displayedTodos[indexPath[0]]
		destination.id = selectedTodo?.id
	}
}
