	//
	//  TodoListModels.swift
	//  TodoList
	//
	//  Created by 60058232 on 2021/01/20.
	//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
	//
	//  This file was generated by the Clean Swift Xcode Templates so
	//  you can apply clean architecture to your iOS and Mac projects,
	//  see http://clean-swift.com
	//

	import UIKit

	enum TodoList
	{
		// MARK: Use cases

		enum FetchTodos
		{
			struct Request
			{
			}
			struct Response
			{
				var todos: [Todo]
			}
			struct ViewModel
			{
				struct DisplayedTodo
				{
                    var id: Int
					var title: String
					var isDone: Bool
					var creationDate : String
				}

				var displayedTodos: [DisplayedTodo]
			}
		}

		enum CheckTodo {
			struct Request
			{
                var id: Int
                var row: Int
			}
			struct Response
			{
				var row: Int
				var todo: Todo
			}
			struct ViewModel
			{
				var row: Int
				var todo: Todo

			}

		}

		enum FetchTodayDate {
			struct Request
			{
			}
			struct Response
			{
				var date: Date
			}
			struct ViewModel
			{
				var todayString: String
			}
		}
	}
