//
//  TodoDetailPresenter.swift
//  TodoList
//
//  Created by 60058232 on 2021/01/22.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoDetailPresentationLogic
{
  func presentTodo(response: TodoDetail.FetchTodo.Response)
}

class TodoDetailPresenter: TodoDetailPresentationLogic
{
  weak var viewController: TodoDetailDisplayLogic?

	let dateFormatter : DateFormatter = {
		let dateFormatter = DateFormatter()
		dateFormatter.locale = Locale(identifier: "ko_KR")
		dateFormatter.dateFormat = "YYYY/M/d h:mm"
		return dateFormatter
	}()
  
  // MARK: - Fetch todo
  
  func presentTodo(response: TodoDetail.FetchTodo.Response)
  {
	let date = dateFormatter.string(from: response.todo.creationDate)

	let viewModel = TodoDetail.FetchTodo.ViewModel(title: response.todo.title ?? "", content: response.todo.content ?? "", creationDate: date)
    viewController?.displayTodo(viewModel: viewModel)
  }
}
