//
//  TodoDetailInteractor.swift
//  TodoList
//
//  Created by 60058232 on 2021/01/22.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoDetailBusinessLogic
{
	func fetchTodo(request: TodoDetail.FetchTodo.Request)
}

protocol TodoDetailDataStore
{
	var id: Int? { get set }
	var todo: Todo? { get set }
}

class TodoDetailInteractor: TodoDetailBusinessLogic, TodoDetailDataStore
{

	var presenter: TodoDetailPresentationLogic?
	var todosWorker = TodosWorker(todosStore: TodoStore())

	var id: Int?
	var todo: Todo?

	// MARK: - fetch todo
	func fetchTodo(request: TodoDetail.FetchTodo.Request)
	{

		if id != nil {
			todosWorker.fetchTodo(id: id!) { (todo) -> Void in
				self.todo = todo!

				let response = TodoDetail.FetchTodo.Response(todo: todo!)
				self.presenter?.presentTodo(response: response)
			}
		}
	}
}
