//
//  CreateTodoInteractor.swift
//  TodoList
//
//  Created by 60058232 on 2021/01/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateTodoBusinessLogic
{
	func createTodo(request: CreateTodo.CreateTodo.Request)
}

protocol CreateTodoDataStore
{
	var todo: Todo? { get set }
}

class CreateTodoInteractor: CreateTodoBusinessLogic, CreateTodoDataStore
{
	var presenter: CreateTodoPresentationLogic?
	var todosWorker = TodosWorker(todosStore: TodoStore())

	var todo: Todo?

	// MARK: Create todo

	func createTodo(request: CreateTodo.CreateTodo.Request) {

		let todoToCreate = Todo(id: 0, content: request.todoField.content, isDone: false, creationDate: Date())

		todosWorker.createTodo(todoToCreate: todoToCreate) { (todo: Todo?) in
			self.todo = todo

			let response = CreateTodo.CreateTodo.Response(todo: todo)
			self.presenter?.presentCreateTodo(response: response)

		}

	}

}
