//
//  CreateTodoModels.swift
//  TodoList
//
//  Created by 60058232 on 2021/01/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateTodo
{
	struct TodoField
	{
		var title: String
		var content: String
	}

	// MARK: Use cases
	enum CreateTodo
	{
		struct Request
		{
			var todoField: TodoField
		}
		struct Response
		{
			var isSuccess: Bool?
		}
		struct ViewModel
		{
			var isSuccess: Bool?
		}
	}
}
