//
//  CreateTodoPresenter.swift
//  TodoList
//
//  Created by 60058232 on 2021/01/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateTodoPresentationLogic
{
	func presentCreateTodo(response: CreateTodo.CreateTodo.Response)
}

class CreateTodoPresenter: CreateTodoPresentationLogic
{

	weak var viewController: CreateTodoDisplayLogic?

	// MARK: Create todo

	func presentCreateTodo(response: CreateTodo.CreateTodo.Response)
	{
		let viewModel = CreateTodo.CreateTodo.ViewModel(todo: response.todo)
		viewController?.displayCreateTodo(viewModel: viewModel)
	}
}
