//
//  CreateTodoRouter.swift
//  TodoList
//
//  Created by 60058232 on 2021/01/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateTodoRoutingLogic
{
	func routeToTodoList(segue: UIStoryboardSegue?)
}

protocol CreateTodoDataPassing
{
	var dataStore: CreateTodoDataStore? { get }
}

class CreateTodoRouter: NSObject, CreateTodoRoutingLogic, CreateTodoDataPassing
{
	weak var viewController: CreateTodoViewController?
	var dataStore: CreateTodoDataStore?

	// MARK: Routing

	func routeToTodoList(segue: UIStoryboardSegue?)
	{
		if let segue = segue {
			let destinationVC = segue.destination as! TodoListViewController
			var destinationDS = destinationVC.router!.dataStore!
			passDataToTodoList(source: dataStore!, destination: &destinationDS)
			destinationVC.refreshTableView()
		} else {
			let storyboard = UIStoryboard(name: "Main", bundle: nil)
			let destinationVC = storyboard.instantiateViewController(withIdentifier: "TodoListViewController") as! TodoListViewController
			var destinationDS = destinationVC.router!.dataStore!
			passDataToTodoList(source: dataStore!, destination: &destinationDS)
			navigateToTodoList(source: viewController!, destination: destinationVC)
		}
	}

	// MARK: Navigation

	func navigateToTodoList(source: CreateTodoViewController, destination: TodoListViewController)
	{
		source.navigationController?.popViewController(animated: true)
	}

	// MARK: Passing data

	func passDataToTodoList(source: CreateTodoDataStore, destination: inout TodoListDataStore)
	{
        if source.todo != nil && destination.todos != nil {
            destination.todos!.append(source.todo!)
		}
	}
}
