//
//  CreateTodoInteractor.swift
//  TodoList
//
//  Created by 60058232 on 2021/01/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateTodoBusinessLogic
{
	func createTodo(request: CreateTodo.CreateTodo.Request)
}

protocol CreateTodoDataStore
{
}

class CreateTodoInteractor: CreateTodoBusinessLogic, CreateTodoDataStore
{
	var presenter: CreateTodoPresentationLogic?
	var todosWorker = TodoWorker(todosStore: TodoStore())

	// MARK: Create todo

	func createTodo(request: CreateTodo.CreateTodo.Request) {

		let title = request.todoField.title
		let content = request.todoField.content

		todosWorker.createTodo(title: title, content: content) { (isSuccess: Bool?) in

			let response = CreateTodo.CreateTodo.Response(isSuccess: isSuccess)
			self.presenter?.presentCreateTodo(response: response)

		}

	}

}
